#!/bin/bash

echo "JILLIAN BARBERIE JILLIAN BARBERIE JILLIAN BARBERIE JILLIAN BARBERIE JILLIAN BARBERIE"
while [ true ] ; do
read -t 1 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "JILLIAN BARBERIE JILLIAN BARBERIE JILLIAN BARBERIE JILLIAN BARBERIE JILLIAN BARBERIE"
fi
done
